### PR TITLE
Expanding Parsing Capability

### PR DESCRIPTION
**Pull request by fhightower**
In this PR, I've done the following:

- Added tests
- Simplified parsing so that it does not parse around line breaks (I very rarely see a use-case for this and from my tests it only creates a lot of false positives)
- Read regexes from `.ini` file
- Allow the user to set the order in which he/she would like indicators to be parsed
- Allow user to specify if an indicator type should be removed from the text once it is parsed (so that it is not also parsed as subsequent indicator types)

### CODE REVIEW

**Comment by fhightower** [comment]
@mosesschwartz If you'd like to keep the package working as it currently is, feel free to let me know and I can start a separate project. My goal is to create a robust package for parsing IOCs in python (you can see some of my objectives here: https://github.com/fhightower/extract_iocs/projects/1).

**Comment by mosesschwartz-rs** [comment]
@fhightower This looks awesome, thank you for the PR! I will be happy to merge, but there are a couple things to address:
- `regexes.ini` needs to be added to setup.py so it can be installed with the package
- The tests don't seem to run happily with modification, either the import should be changed from `from extract_iocs import extract_iocs` to `import extract_iocs` or the test functions should just call `extract_iocs` instead of `extract_iocs.extract_iocs(apt28.read())`

**Comment by mosesschwartz** [comment]
@fhightower This looks awesome, thank you for the PR! I will be happy to merge, but there are a couple things to address:
- `regexes.ini` needs to be added to setup.py so it can be installed with the package
- The tests don't seem to run happily with modification, either the import should be changed from `from extract_iocs import extract_iocs` to `import extract_iocs` or the test functions should just call `extract_iocs` instead of `extract_iocs.extract_iocs(apt28.read())`

(Apologize for the double notification, I accidentally commented with my work account first, then deleted that comment)

**Comment by fhightower** [comment]
Ah, of course. Thanks for the notes. I'll make those changes.

**Comment by fhightower** [comment]
Thanks again for the feedback @mosesschwartz ! I've made the changes you suggested.

**Pull request merged**
